server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D'

spring:
  datasource:
    url: jdbc:postgresql://dpg-d7fq4qs71suc73bgp0og-a:5432/doctracker
    username: doctracker
    password: ZasVdMNSqtAym6ATfjKHG6v8ywdvBzNh
    hikari:
      data-source-properties:
        sslmode: require

app:
  jwt:
    secret: ${APP_JWT_SECRET:}
    access-token-ttl: 30m
  gemini:
    api-key: ${APP_GEMINI_API_KEY:}
    model: ${APP_GEMINI_MODEL:gemini-2.5-flash-lite}

logging:
  level:
    com.docutrack: DEBUG
    org.springframework.web: INFO
